# This config should be put in /etc/greetd/

[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
# command = "agreety --cmd /bin/sh"

command = "tuigreet --cmd /usr/local/bin/start-sway"
# The `start-sway` script is required in order to properly load the environment variables.

user = "greeter"
